# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCLVvhROOYnS93ycct2twbNmamslN6OA
"""

print ("hello world!")

print ("I Am Supream")

a = 7
print(a)

a=6
print(a*a*(a+1)/2)

a=input()
b=input()
sum=input()
print(a+b+c)

a=5
b=10
print(a,b)
a=a+b
b=a-b
a=a-b
print(a,b)

print("even odd")
a=0
while(a<=10):
 if(a%2==0):
  print(a,"  ",a+1)
 a=a+1

a=0
while(a<=10):
 if(a%2==0):
  print(a,"is even")
 else:
  print(a,"is odd")
 a=a+1

a=input()
if(a=="sun") :
  print ("sunday")
elif(a=="mon") :
  print ("monday")
elif(a=="tue") :
  print ("tuesday")
elif(a=="wed") :
  print ("wednesday")
elif(a=="thur") :
  print ("thursday")
elif(a=="fri") :
  print ("friday")
else :
  print ("saturday")

for i in range(10) :
  print(i)

# for i in range(start,end,step(gap)) :
for i in range(0,11,2) :
  print(i)

# a++ do not work with python use a=a+x
#but we have / will give decimal result , // will give integer result
#similarily * means multiplication & ** means power
a=0
while a<10 :
  print(a)
  a=a+1

a=input()
n=len(a)
n=n-1
for i in range (0,n+1) :
  if (a[i]!=a[n]):
    print ("false")
    break
  elif (i==n):
    print ("true")
    break
  else :
    i=i + 1
    n=n - 1

